<a href="https://colab.research.google.com/github/ManarAlmusalam-uni/NLP-Lab5/blob/main/Lab5_Text_Representation_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Representation

Text representation in NLP means converting text into a numerical form that a machine learning model can understand and process.

## What is Embedding?

Embeddings in NLP is a technique where individual words are represented as real-valued vectors and captures inter-word semantics.


In this notebook, We going to intreduce 2 techniques for embedding. These techniques will be used for a machine learning models such as SVM, Random forest, ... ect.

<img src="https://drive.google.com/uc?export=view&id=1jd0u_sGppDKqBYbhtJfGxp14lnUWUTTw" width="900">

# 1- TF-IDF

<img src="https://drive.google.com/uc?export=view&id=1saSt0mMgOQ2ybbTms1lu_ruhUcBWkKzL" width="500">

TF-IDF stands for term frequency-inverse document frequency. It is a measure that discounts common words. Used in the fields of information retrieval (IR) and machine learning, that can quantify the importance of words in a document amongst a collection of documents (also known as a corpus).

### Components of TF-IDF

1. **TF (Term Frequency):**  
   Measures how frequently a term appears in a document.


$$ \text{TF}(t, d) = \frac{\text{Number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d} $$


2. **IDF (Inverse Document Frequency):**  
   Measures how important a term is across all documents. Words that appear in many documents get lower scores.

$$    \text{IDF}(t) = \log \left(\frac{\text{Number of all documents N}}{\text{Number of documents containing the term } t}\right) $$

<img src="https://drive.google.com/uc?export=view&id=1JqPILC8TTh3yDQZCSuPNXwm6ER5YeJFh" width="900">

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [ ]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(data) # returns sparce matrix

In [ ]:
df = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df

       data  digital  economy        is       new       of       oil      the
0  0.243777  0.34262  0.34262  0.243777  0.000000  0.34262  0.243777  0.68524
1  0.448321  0.00000  0.00000  0.448321  0.630099  0.00000  0.448321  0.00000

In [ ]:
df = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df

       data  digital  economy        is       new       of       oil      the
0  0.243777  0.34262  0.34262  0.243777  0.000000  0.34262  0.243777  0.68524
1  0.448321  0.00000  0.00000  0.448321  0.630099  0.00000  0.448321  0.00000

# Cosine similarity

In NLP, Cosine similarity is a metric used to measure how similar the documents are.


$$ \text{cosine similarity} = \frac{A \cdot B}{\|A\| \times \|B\|} $$

Where:  
$ A \cdot B $  = dot product of vectors A and B  
$ \|A\| $ = magnitude (length) of vector A  
$ \|B\| $ =  magnitude (length) of vector B

#### Intuition

- If vectors point in the **same direction**, cosine similarity = **1** (maximum similarity).
- If vectors are **orthogonal (90° apart)**, cosine similarity = **0** (no similarity).

<img src="https://drive.google.com/uc?export=view&id=1b-o8CVfHBsjUGY_hXmxevU91gHidIuxO" width="900">

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:

doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [ ]:
tfidf_vectorizer = TfidfVectorizer() # Create a CountVectorizer instance
vector_matrix = tfidf_vectorizer.fit_transform(data) # Fit and transform the documents into numerical vectors

In [ ]:
# Calculate the cosine similarity between the documents
cosine_similarity_matrix = cosine_similarity(vector_matrix)

df_cosine = pd.DataFrame(data=cosine_similarity_matrix, index=data, columns=data)

df_cosine

,Data is the oil of the digital economy,Data is a new oil
Data is the oil of the digital economy,1.000000,0.327871
Data is a new oil,0.327871,1.000000

In [ ]:
# Calculate the cosine similarity between the documents
cosine_similarity_matrix = cosine_similarity(vector_matrix)

df_cosine = pd.DataFrame(data=cosine_similarity_matrix, index=data, columns=data)

df_cosine

,Data is the oil of the digital economy,Data is a new oil
Data is the oil of the digital economy,1.000000,0.327871
Data is a new oil,0.327871,1.000000

# 2- What is Word2vec?

Word2Vec consists of models for generating word embedding. These models are two-layer neural networks having one input layer, one hidden layer, and one output layer.

Word2Vec utilizes two architectures :
1. CBOW (Continuous Bag of Words)
2. **Skip Gram**
<img src="https://drive.google.com/uc?export=view&id=1K38nEu_KhgtSJuG2RySwc6U5AAjVAgWZ" width="600">


Run this command in terminal to install
> pip install gensim

We will use fake and real news dataset to do our expirament. You can find the dataset here: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset?select=True.csv

In [1]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.4.0)
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 34.2 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [14]:
import pandas as pd
import nltk
import numpy as np
import gensim

from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("clmentbisaillon/fake-and-real-news-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'fake-and-real-news-dataset' dataset.
Path to dataset files: /kaggle/input/fake-and-real-news-dataset

In [4]:
import os
import pandas as pd

print(os.listdir(path))

['True.csv', 'Fake.csv']

In [10]:
true_df = pd.read_csv(os.path.join(path, 'True.csv'))
true_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [11]:
fake_df = pd.read_csv(os.path.join(path, 'Fake.csv'))
fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [18]:

# Add labels
true_df['label'] = 1
fake_df['label'] = 0

# Combine both datasets
df = pd.concat([true_df, fake_df], ignore_index=True)

# Tokenize the news text
tokens = []

for text in df['text'].dropna():
    token = word_tokenize(text)
    tokens.append(token)

print(tokens[:2])

[['WASHINGTON', '(', 'Reuters', ')', '-', 'The', 'head', 'of', 'a', 'conservative', 'Republican', 'faction', 'in', 'the', 'U.S.', 'Congress', ',', 'who', 'voted', 'this', 'month', 'for', 'a', 'huge', 'expansion', 'of', 'the', 'national', 'debt', 'to', 'pay', 'for', 'tax', 'cuts', ',', 'called', 'himself', 'a', '“', 'fiscal', 'conservative', '”', 'on', 'Sunday', 'and', 'urged', 'budget', 'restraint', 'in', '2018', '.', 'In', 'keeping', 'with', 'a', 'sharp', 'pivot', 'under', 'way', 'among', 'Republicans', ',', 'U.S.', 'Representative', 'Mark', 'Meadows', ',', 'speaking', 'on', 'CBS', '’', '“', 'Face', 'the', 'Nation', ',', '”', 'drew', 'a', 'hard', 'line', 'on', 'federal', 'spending', ',', 'which', 'lawmakers', 'are', 'bracing', 'to', 'do', 'battle', 'over', 'in', 'January', '.', 'When', 'they', 'return', 'from', 'the', 'holidays', 'on', 'Wednesday', ',', 'lawmakers', 'will', 'begin', 'trying', 'to', 'pass', 'a', 'federal', 'budget', 'in', 'a', 'fight', 'likely', 'to', 'be', 'linked', 'to', 'other', 'issues', ',', 'such', 'as', 'immigration', 'policy', ',', 'even', 'as', 'the', 'November', 'congressional', 'election', 'campaigns', 'approach', 'in', 'which', 'Republicans', 'will', 'seek', 'to', 'keep', 'control', 'of', 'Congress', '.', 'President', 'Donald', 'Trump', 'and', 'his', 'Republicans', 'want', 'a', 'big', 'budget', 'increase', 'in', 'military', 'spending', ',', 'while', 'Democrats', 'also', 'want', 'proportional', 'increases', 'for', 'non-defense', '“', 'discretionary', '”', 'spending', 'on', 'programs', 'that', 'support', 'education', ',', 'scientific', 'research', ',', 'infrastructure', ',', 'public', 'health', 'and', 'environmental', 'protection', '.', '“', 'The', '(', 'Trump', ')', 'administration', 'has', 'already', 'been', 'willing', 'to', 'say', ':', '‘', 'We', '’', 're', 'going', 'to', 'increase', 'non-defense', 'discretionary', 'spending', '...', 'by', 'about', '7', 'percent', ',', '’', '”', 'Meadows', ',', 'chairman', 'of', 'the', 'small', 'but', 'influential', 'House', 'Freedom', 'Caucus', ',', 'said', 'on', 'the', 'program', '.', '“', 'Now', ',', 'Democrats', 'are', 'saying', 'that', '’', 's', 'not', 'enough', ',', 'we', 'need', 'to', 'give', 'the', 'government', 'a', 'pay', 'raise', 'of', '10', 'to', '11', 'percent', '.', 'For', 'a', 'fiscal', 'conservative', ',', 'I', 'don', '’', 't', 'see', 'where', 'the', 'rationale', 'is', '.', '...', 'Eventually', 'you', 'run', 'out', 'of', 'other', 'people', '’', 's', 'money', ',', '”', 'he', 'said', '.', 'Meadows', 'was', 'among', 'Republicans', 'who', 'voted', 'in', 'late', 'December', 'for', 'their', 'party', '’', 's', 'debt-financed', 'tax', 'overhaul', ',', 'which', 'is', 'expected', 'to', 'balloon', 'the', 'federal', 'budget', 'deficit', 'and', 'add', 'about', '$', '1.5', 'trillion', 'over', '10', 'years', 'to', 'the', '$', '20', 'trillion', 'national', 'debt', '.', '“', 'It', '’', 's', 'interesting', 'to', 'hear', 'Mark', 'talk', 'about', 'fiscal', 'responsibility', ',', '”', 'Democratic', 'U.S.', 'Representative', 'Joseph', 'Crowley', 'said', 'on', 'CBS', '.', 'Crowley', 'said', 'the', 'Republican', 'tax', 'bill', 'would', 'require', 'the', 'United', 'States', 'to', 'borrow', '$', '1.5', 'trillion', ',', 'to', 'be', 'paid', 'off', 'by', 'future', 'generations', ',', 'to', 'finance', 'tax', 'cuts', 'for', 'corporations', 'and', 'the', 'rich', '.', '“', 'This', 'is', 'one', 'of', 'the', 'least', '...', 'fiscally', 'responsible', 'bills', 'we', '’', 've', 'ever', 'seen', 'passed', 'in', 'the', 'history', 'of', 'the', 'House', 'of', 'Representatives', '.', 'I', 'think', 'we', '’', 're', 'going', 'to', 'be', 'paying', 'for', 'this', 'for', 'many', ',', 'many', 'years', 'to', 'come', ',', '”', 'Crowley', 'said', '.', 'Republicans', 'insist', 'the', 'tax', 'package', ',', 'the', 'biggest', 'U.S.', 'tax', 'overhaul', 'in', 'more', 'than', '30', 'years', ',', 'will', 'boost', 'the', 'economy', 'and', 'job', 'growth', '.', 'House', 'Speaker', 'Paul', 'Ryan', ',', 'who', 'also', 'supported', 'the', 'tax', 'bill', ',', 'recently', 'went', 'further', 'than', 'Meadows', ',', 'making', 'clear', 'in', 'a', 'radio', 'interview', 'that', 'welfare', 'or', '“', 'entitlement', 'reform', ',', '”', 'as', 'the', 'party', 'often', 'calls', 'it', ',', 'would', 'be', 'a', 'top', 'Republican', 'priority', 'in', '2018', '.', 'In', 'Republican', 'parlance', ',', '“', 'entitlement', '”', 'programs', 'mean', 'food', 'stamps', ',', 'housing', 'assistance', ',', 'Medicare', 'and', 'Medicaid', 'health', 'insurance', 'for', 'the', 'elderly', ',', 'poor', 'and', 'disabled', ',', 'as', 'well', 'as', 'other', 'programs', 'created', 'by', 'Washington', 'to', 'assist', 'the', 'needy', '.', 'Democrats', 'seized', 'on', 'Ryan', '’', 's', 'early', 'December', 'remarks', ',', 'saying', 'they', 'showed', 'Republicans', 'would', 'try', 'to', 'pay', 'for', 'their', 'tax', 'overhaul', 'by', 'seeking', 'spending', 'cuts', 'for', 'social', 'programs', '.', 'But', 'the', 'goals', 'of', 'House', 'Republicans', 'may', 'have', 'to', 'take', 'a', 'back', 'seat', 'to', 'the', 'Senate', ',', 'where', 'the', 'votes', 'of', 'some', 'Democrats', 'will', 'be', 'needed', 'to', 'approve', 'a', 'budget', 'and', 'prevent', 'a', 'government', 'shutdown', '.', 'Democrats', 'will', 'use', 'their', 'leverage', 'in', 'the', 'Senate', ',', 'which', 'Republicans', 'narrowly', 'control', ',', 'to', 'defend', 'both', 'discretionary', 'non-defense', 'programs', 'and', 'social', 'spending', ',', 'while', 'tackling', 'the', 'issue', 'of', 'the', '“', 'Dreamers', ',', '”', 'people', 'brought', 'illegally', 'to', 'the', 'country', 'as', 'children', '.', 'Trump', 'in', 'September', 'put', 'a', 'March', '2018', 'expiration', 'date', 'on', 'the', 'Deferred', 'Action', 'for', 'Childhood', 'Arrivals', ',', 'or', 'DACA', ',', 'program', ',', 'which', 'protects', 'the', 'young', 'immigrants', 'from', 'deportation', 'and', 'provides', 'them', 'with', 'work', 'permits', '.', 'The', 'president', 'has', 'said', 'in', 'recent', 'Twitter', 'messages', 'he', 'wants', 'funding', 'for', 'his', 'proposed', 'Mexican', 'border', 'wall', 'and', 'other', 'immigration', 'law', 'changes', 'in', 'exchange', 'for', 'agreeing', 'to', 'help', 'the', 'Dreamers', '.', 'Representative', 'Debbie', 'Dingell', 'told', 'CBS', 'she', 'did', 'not', 'favor', 'linking', 'that', 'issue', 'to', 'other', 'policy', 'objectives', ',', 'such', 'as', 'wall', 'funding', '.', '“', 'We', 'need', 'to', 'do', 'DACA', 'clean', ',', '”', 'she', 'said', '.', 'On', 'Wednesday', ',', 'Trump', 'aides', 'will', 'meet', 'with', 'congressional', 'leaders', 'to', 'discuss', 'those', 'issues', '.', 'That', 'will', 'be', 'followed', 'by', 'a', 'weekend', 'of', 'strategy', 'sessions', 'for', 'Trump', 'and', 'Republican', 'leaders', 'on', 'Jan.', '6', 'and', '7', ',', 'the', 'White', 'House', 'said', '.', 'Trump', 'was', 'also', 'scheduled', 'to', 'meet', 'on', 'Sunday', 'with', 'Florida', 'Republican', 'Governor', 'Rick', 'Scott', ',', 'who', 'wants', 'more', 'emergency', 'aid', '.', 'The', 'House', 'has', 'passed', 'an', '$', '81', 'billion', 'aid', 'package', 'after', 'hurricanes', 'in', 'Florida', ',', 'Texas', 'and', 'Puerto', 'Rico', ',', 'and', 'wildfires', 'in', 'California', '.', 'The', 'package', 'far', 'exceeded', 'the', '$', '44', 'billion', 'requested', 'by', 'the', 'Trump', 'administration', '.', 'The', 'Senate', 'has', 'not', 'yet', 'voted', 'on', 'the', 'aid', '.'], ['WASHINGTON', '(', 'Reuters', ')', '-', 'Transgender', 'people', 'will', 'be', 'allowed', 'for', 'the', 'first', 'time', 'to', 'enlist', 'in', 'the', 'U.S.', 'military', 'starting', 'on', 'Monday', 'as', 'ordered', 'by', 'federal', 'courts', ',', 'the', 'Pentagon', 'said', 'on', 'Friday', ',', 'after', 'President', 'Donald', 'Trump', '’', 's', 'administration', 'decided', 'not', 'to', 'appeal', 'rulings', 'that', 'blocked', 'his', 'transgender', 'ban', '.', 'Two', 'federal', 'appeals', 'courts', ',', 'one', 'in', 'Washington', 'and', 'one', 'in', 'Virginia', ',', 'last', 'week', 'rejected', 'the', 'administration', '’', 's', 'request', 'to', 'put', 'on', 'hold', 'orders', 'by', 'lower', 'court', 'judges', 'requiring', 'the', 'military', 'to', 'begin', 'accepting', 'transgender', 'recruits', 'on', 'Jan.', '1', '.', 'A', 'Justice', 'Department', 'official', 'said', 'the', 'administration', 'will', 'not', 'challenge', 'those', 'rulings', '.', '“', 'The', 'Department', 'of', 'Defense', 'has', 'announced', 'that', 'it', 'will', 'be', 'releasing', 'an', 'independent', 'study', 'of', 'these', 'issues', 'in', 'the', 'coming', 'weeks', '.', 'So', 'rather', 'than', 'litigate', 'this', 'interim', 'appeal', 'before', 'that', 'occurs', ',', 'the', 'administration', 'has', 'decided', 'to', 'wait', 'for', 'DOD', '’', 's', 'study', 'and', 'will', 'continue', 'to', 'defend', 'the', 'president', '’', 's', 'lawful', 'authority', 'in', 'District', 'Court', 'in', 'the', 'meantime', ',', '”', 'the', 'official', 'said', ',', 'speaking', 'on', 'condition', 'of', 'anonymity', '.', 'In', 'September', ',', 'the', 'Pentagon', 'said', 'it', 'had', 'created', 'a', 'panel', 'of', 'senior', 'officials', 'to', 'study', 'how', 'to', 'implement', 'a', 'directive', 'by', 'Trump', 'to', 'prohibit', 'transgender', 'individuals', 'from', 'serving', '.', 'The', 'Defense', 'Department', 'has', 'until', 'Feb.', '21', 'to', 'submit', 'a', 'plan', 'to', 'Trump', '.', 'Lawyers', 'representing', 'currently-serving', 'transgender', 'service', 'members', 'and', 'aspiring', 'recruits', 'said', 'they', 'had', 'expected', 'the', 'administration', 'to', 'appeal', 'the', 'rulings', 'to', 'the', 'conservative-majority', 'Supreme', 'Court', ',', 'but', 'were', 'hoping', 'that', 'would', 'not', 'happen', '.', 'Pentagon', 'spokeswoman', 'Heather', 'Babb', 'said', 'in', 'a', 'statement', ':', '“', 'As', 'mandated', 'by', 'court', 'order', ',', 'the', 'Department', 'of', 'Defense', 'is', 'prepared', 'to', 'begin', 'accessing', 'transgender', 'applicants', 'for', 'military', 'service', 'Jan.', '1', '.', 'All', 'applicants', 'must', 'meet', 'all', 'accession', 'standards.', '”', 'Jennifer', 'Levi', ',', 'a', 'lawyer', 'with', 'gay', ',', 'lesbian', 'and', 'transgender', 'advocacy', 'group', 'GLAD', ',', 'called', 'the', 'decision', 'not', 'to', 'appeal', '“', 'great', 'news.', '”', '“', 'I', '’', 'm', 'hoping', 'it', 'means', 'the', 'government', 'has', 'come', 'to', 'see', 'that', 'there', 'is', 'no', 'way', 'to', 'justify', 'a', 'ban', 'and', 'that', 'it', '’', 's', 'not', 'good', 'for', 'the', 'military', 'or', 'our', 'country', ',', '”', 'Levi', 'said', '.', 'Both', 'GLAD', 'and', 'the', 'American', 'Civil', 'Liberties', 'Union', 'represent', 'plaintiffs', 'in', 'the', 'lawsuits', 'filed', 'against', 'the', 'administration', '.', 'In', 'a', 'move', 'that', 'appealed', 'to', 'his', 'hard-line', 'conservative', 'supporters', ',', 'Trump', 'announced', 'in', 'July', 'that', 'he', 'would', 'prohibit', 'transgender', 'people', 'from', 'serving', 'in', 'the', 'military', ',', 'reversing', 'Democratic', 'President', 'Barack', 'Obama', '’', 's', 'policy', 'of', 'accepting', 'them', '.', 'Trump', 'said', 'on', 'Twitter', 'at', 'the', 'time', 'that', 'the', 'military', '“', 'can', 'not', 'be', 'burdened', 'with', 'the', 'tremendous', 'medical', 'costs', 'and', 'disruption', 'that', 'transgender', 'in', 'the', 'military', 'would', 'entail.', '”', 'Four', 'federal', 'judges', '-', 'in', 'Baltimore', ',', 'Washington', ',', 'D.C.', ',', 'Seattle', 'and', 'Riverside', ',', 'California', '-', 'have', 'issued', 'rulings', 'blocking', 'Trump', '’', 's', 'ban', 'while', 'legal', 'challenges', 'to', 'the', 'Republican', 'president', '’', 's', 'policy', 'proceed', '.', 'The', 'judges', 'said', 'the', 'ban', 'would', 'likely', 'violate', 'the', 'right', 'under', 'the', 'U.S.', 'Constitution', 'to', 'equal', 'protection', 'under', 'the', 'law', '.', 'The', 'Pentagon', 'on', 'Dec.', '8', 'issued', 'guidelines', 'to', 'recruitment', 'personnel', 'in', 'order', 'to', 'enlist', 'transgender', 'applicants', 'by', 'Jan.', '1', '.', 'The', 'memo', 'outlined', 'medical', 'requirements', 'and', 'specified', 'how', 'the', 'applicants', '’', 'sex', 'would', 'be', 'identified', 'and', 'even', 'which', 'undergarments', 'they', 'would', 'wear', '.', 'The', 'Trump', 'administration', 'previously', 'said', 'in', 'legal', 'papers', 'that', 'the', 'armed', 'forces', 'were', 'not', 'prepared', 'to', 'train', 'thousands', 'of', 'personnel', 'on', 'the', 'medical', 'standards', 'needed', 'to', 'process', 'transgender', 'applicants', 'and', 'might', 'have', 'to', 'accept', '“', 'some', 'individuals', 'who', 'are', 'not', 'medically', 'fit', 'for', 'service.', '”', 'The', 'Obama', 'administration', 'had', 'set', 'a', 'deadline', 'of', 'July', '1', ',', '2017', ',', 'to', 'begin', 'accepting', 'transgender', 'recruits', '.', 'But', 'Trump', '’', 's', 'defense', 'secretary', ',', 'James', 'Mattis', ',', 'postponed', 'that', 'date', 'to', 'Jan.', '1', ',', '2018', ',', 'which', 'the', 'president', '’', 's', 'ban', 'then', 'put', 'off', 'indefinitely', '.', 'Trump', 'has', 'taken', 'other', 'steps', 'aimed', 'at', 'rolling', 'back', 'transgender', 'rights', '.', 'In', 'October', ',', 'his', 'administration', 'said', 'a', 'federal', 'law', 'banning', 'gender-based', 'workplace', 'discrimination', 'does', 'not', 'protect', 'transgender', 'employees', ',', 'reversing', 'another', 'Obama-era', 'position', '.', 'In', 'February', ',', 'Trump', 'rescinded', 'guidance', 'issued', 'by', 'the', 'Obama', 'administration', 'saying', 'that', 'public', 'schools', 'should', 'allow', 'transgender', 'students', 'to', 'use', 'the', 'restroom', 'that', 'corresponds', 'to', 'their', 'gender', 'identity', '.']]

In [19]:
w2v = gensim.models.Word2Vec(tokens, min_count=1, vector_size=100, window=5, sg=1)

In [20]:
print("Cosine similarity between 'provide' and 'program' - Skip Gram : ",w2v.wv.similarity('provide', 'program'))

Cosine similarity between 'provide' and 'program' - Skip Gram :  0.49144375

In [21]:
print("words that similar to 'program' - Skip Gram : ",w2v.wv.most_similar('program'))

words that similar to 'program' - Skip Gram :  [('programs', 0.7959345579147339), ('programme', 0.7801445126533508), ('program.The', 0.7129901647567749), ('EB-5', 0.7083961963653564), ('expiring', 0.7010190486907959), ('guest-worker', 0.6954377889633179), ('bond-buying', 0.6915661096572876), ('government-run', 0.6826795935630798), ('PEP', 0.6794056296348572), ('Program', 0.6743077039718628)]

In [ ]:
df = pd.read_csv('/content/True.csv', engine='python', on_bad_lines='skip') #fake-and-real-news-dataset-true.csv
df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [16]:
tokens = []

for i in df['text']:
    token = word_tokenize(i)
    tokens.append(token)

In [ ]:
w2v = gensim.models.Word2Vec(tokens, min_count=1, vector_size=100, window=5, sg=1)

In [ ]:
print("Cosine similarity between 'provide' and 'program' - Skip Gram : ",w2v.wv.similarity('provide', 'program'))

Cosine similarity between 'provide' and 'program' - Skip Gram :  0.41992348

In [ ]:
print("words that similar to 'program' - Skip Gram : ",w2v.wv.most_similar('program'))

words that similar to 'program' - Skip Gram :  [('programs', 0.7426663041114807), ('programme', 0.687917172908783), ('guest-worker', 0.6685435771942139), ('EB-5', 0.66179358959198), ('seniors', 0.6605323553085327), ('arsenal', 0.659981906414032), ('expanding', 0.6542479395866394), ('abolishing', 0.6510066390037537), ('plan', 0.6469865441322327), ('marketplaces', 0.6462255120277405)]

# Tasks

### Task 1: Cosine Similarity
Use the Cosine Similarity method to determine how similar the following sentences are.

'This is the first document.',  
'This document is the second document.',  
'And this is the third one.',  
'Is this the first document?'

In [22]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
sentences = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?'
]

In [24]:
tfidf = TfidfVectorizer()
vector_matrix = tfidf.fit_transform(sentences)

In [25]:
cosine_similarity_matrix = cosine_similarity(vector_matrix)

In [26]:

df_cosine = pd.DataFrame(
    cosine_similarity_matrix,
    index=['Document 1', 'Document 2', 'Document 3', 'Document 4'],
    columns=['Document 1', 'Document 2', 'Document 3', 'Document 4']
)

df_cosine

            Document 1  Document 2  Document 3  Document 4
Document 1    1.000000    0.646926    0.307772    1.000000
Document 2    0.646926    1.000000    0.225240    0.646926
Document 3    0.307772    0.225240    1.000000    0.307772
Document 4    1.000000    0.646926    0.307772    1.000000

### Task 2: TF-IDF
Use tf-idf method on the sentences below to determine the important words.

'data science is one of the most important fields of science',  
'this is one of the best data science courses',  
'data scientists analyze data'

In [27]:
sentences = [
    'data science is one of the most important fields of science',
    'this is one of the best data science courses',
    'data scientists analyze data'
]

In [28]:
tfidf = TfidfVectorizer()

In [29]:
result = tfidf.fit_transform(sentences)

In [30]:
df_tfidf = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df_tfidf

,analyze,best,courses,data,fields,important,is,most,of,one,science,scientists,the,this
0,0.000000,0.000000,0.000000,0.189526,0.320895,0.320895,0.244049,0.320895,0.488098,0.244049,0.488098,0.000000,0.244049,0.000000
1,0.000000,0.400294,0.400294,0.236420,0.000000,0.000000,0.304434,0.000000,0.304434,0.304434,0.304434,0.000000,0.304434,0.400294
2,0.542701,0.000000,0.000000,0.641055,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.542701,0.000000,0.000000

## Word2vec

### Task 3:

Download the Simpsons dataset **(simpsons_script_lines.csv)** and apply the preprocessing procedure.  
Use the **'spoken_words'** column.
```
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text
```
Create a skip gram Word2Vec model as below.
```
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count = 1, vector_size = 100, window = 5, sg = 1)

In [31]:
from google.colab import files

uploaded = files.upload()

Saving simpsons_script_lines.csv to simpsons_script_lines.csv

In [33]:
import pandas as pd
import re
import nltk
import gensim

from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [34]:
df = pd.read_csv('simpsons_script_lines.csv')
df.head()

        raw_character_text                                       spoken_words
0              Miss Hoover  No, actually, it was a little of both. Sometim...
1             Lisa Simpson                             Where's Mr. Bergstrom?
2              Miss Hoover  I don't know. Although I'd sure like to talk t...
3             Lisa Simpson                         That life is worth living.
4  Edna Krabappel-Flanders  The polls will be open from now until the end ...

In [35]:
print(df.columns)

Index(['raw_character_text', 'spoken_words'], dtype='object')

In [36]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text

In [37]:
df['cleaned_text'] = df['spoken_words'].dropna().apply(clean_text)

In [38]:
df = df.dropna(subset=['spoken_words'])

df['cleaned_text'] = df['spoken_words'].apply(clean_text)

In [39]:
df[['spoken_words', 'cleaned_text']].head()

,spoken_words,cleaned_text
0,"No, actually, it was a little of both. Sometim...",no actually it was a little of both sometimes ...
1,Where's Mr. Bergstrom?,where's mr bergstrom?
2,I don't know. Although I'd sure like to talk t...,i don't know although i'd sure like to talk to...
3,That life is worth living.,that life is worth living
4,The polls will be open from now until the end ...,the polls will be open from now until the end ...

In [40]:
tokens = []

for text in df['cleaned_text']:
    token = word_tokenize(text)
    tokens.append(token)

In [41]:
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count=1, vector_size=100, window=5, sg=1)

### Task 4

Use: wv.most_similar() method to :

1.	Find the words similar to “homer”.

2.	Find the words similar to “marge”.

3. Find the words similar to “bart”

In [43]:
print("Words similar to 'homer':")
print(Skip_gram_model.wv.most_similar('homer'))

Words similar to 'homer':
[('abe', 0.871264636516571), ('marge', 0.8435773849487305), ('grampa', 0.8244199752807617), ('eliza', 0.824233889579773), ('ned', 0.8157385587692261), ('barney', 0.8139645457267761), ('bartholomew', 0.8113955855369568), ('pal', 0.8108170032501221), ('lurleen', 0.80464768409729), ('midge', 0.8023056983947754)]

In [46]:
print("Words similar to 'marge':")
print(Skip_gram_model.wv.most_similar('marge'))

Words similar to 'marge':
[('homer', 0.8435773253440857), ('abe', 0.8393473029136658), ('sweetie', 0.8317261934280396), ('becky', 0.8199036121368408), ('honey', 0.8052301406860352), ('midge', 0.8035217523574829), ('lurleen', 0.7992222905158997), ('maude', 0.7988554239273071), ('agnes', 0.7954486012458801), ('lisa', 0.7941148281097412)]

In [47]:
print("Words similar to 'bart':")
print(Skip_gram_model.wv.most_similar('bart'))

Words similar to 'bart':
[('milhouse', 0.8714122772216797), ('lisa', 0.8710554838180542), ('grampa', 0.837428867816925), ('sweetie', 0.8223322033882141), ('eliza', 0.8196548819541931), ('laddie', 0.8182199001312256), ('abe', 0.8161525726318359), ('jessica', 0.8120670914649963), ('janey', 0.8106374144554138), ('stampy', 0.8084563612937927)]

### Task 5

Use the wv.doesnt_match() method to :

1.	Find which of 'jimbo', 'milhouse’, and 'kearney’ does not belong to the list.

3.	Find the odd one among "nelson", "bart", and "milhouse".

4.	Find the odd one among ‘homer', 'patty', and ‘selma'.

*Hint: You need to pass the strings as List*

In [48]:
print(Skip_gram_model.wv.doesnt_match(['jimbo', 'milhouse', 'kearney']))

milhouse

In [49]:
print(Skip_gram_model.wv.doesnt_match(['nelson', 'bart', 'milhouse']))

nelson

In [50]:
print(Skip_gram_model.wv.doesnt_match(['homer', 'patty', 'selma']))

homer